// @ts-check
import { defineConfig, sessionDrivers } from 'astro/config';
import cloudflare from '@astrojs/cloudflare';
import sitemap from '@astrojs/sitemap';
import { satteri } from '@astrojs/markdown-satteri';
import { hastMedia } from './src/lib/hast-media.mjs';
import { lastmodByRoute } from './src/lib/lastmod.mjs';
import { noindexLegalRoutes } from './src/lib/legal-routes.mjs';

// The build environment is the single source of truth for what this deploy
// *is*. Nothing downstream re-derives it, and nothing is toggled by hand.
const SITE_ENV = process.env.PUBLIC_SITE_ENV ?? 'development';

/*
 * Refuse to BUILD for a deploy without saying which deploy it is.
 *
 * `development` resolves the site URL to http://localhost:4321, so a build with
 * no environment emits canonical tags pointing at localhost. It builds clean,
 * deploys clean, and is wrong.
 *
 * ── WHY THIS KEYS ON THE COMMAND AND NOT ON `CI` ───────────────────────────
 * It used to be `if (process.env.CI && …)`, which left the hole wide open on
 * the machine where it is most likely to be walked into. `npm run build` is the
 * most reflexive command in the npm ecosystem, and here it produced a
 * development build in silence — verified: canonical `http://localhost:4321/`,
 * exit 0, no warning. `npx astro build` did the same. The kit's own README
 * claimed this was already guarded.
 *
 * Keying on the argv command closes both, and leaves `astro dev` alone, where
 * `development` is the correct answer rather than a missing one.
 */
const isBuilding = process.argv.some((a) => a === 'build');

if (isBuilding && SITE_ENV === 'development') {
  throw new Error(
    'PUBLIC_SITE_ENV is not set.\n\n' +
      'A build must declare its environment, or it emits localhost canonical\n' +
      'URLs — cleanly, with no error, and wrong. Use one of:\n\n' +
      '  npm run build:staging      → new.example.com, noindex\n' +
      '  npm run build:production   → example.com, indexable\n\n' +
      'On Cloudflare Workers Builds, that is the build command in the dashboard.\n' +
      'For a one-off local build, set it inline:\n\n' +
      '  PUBLIC_SITE_ENV=staging npx astro build\n',
  );
}
const SITE_URL =
  process.env.PUBLIC_SITE_URL ??
  (SITE_ENV === 'production'
    ? 'https://example.com'
    : SITE_ENV === 'staging'
      ? 'https://new.example.com'
      : 'http://localhost:4321');

const isProduction = SITE_ENV === 'production';

/*
 * Per-page `lastmod` for the sitemap, from src/data/lastmod.json.
 *
 * Generated by `npm run lastmod` and COMMITTED — never read from git at build
 * time. CI shallow-clones, so `git log` there returns one grafted commit for
 * every file and every page would claim the same date. An empty map means no
 * `lastmod` is emitted at all, which is the correct outcome: a sitemap saying
 * "I don't know" is honest, one claiming every page changed today is not, and
 * Google discounts a file whose dates are not consistently accurate.
 */
const LASTMOD = lastmodByRoute();

/** Legal pages that must exist and must not be indexed. See legal-routes.mjs. */
const NOINDEX_LEGAL = noindexLegalRoutes();

export default defineConfig({
  site: SITE_URL,
  output: 'static',

  /*
   * This site has no sessions. Left unset, the Cloudflare adapter helpfully
   * configures a KV session driver and writes a `SESSION` kv_namespace binding
   * with NO id into the generated wrangler.json — which wrangler then *creates*
   * on deploy. That works exactly once: the namespace outlives the worker, so
   * tearing the deployment down and recreating it from git fails on a name the
   * previous incarnation left behind. The null driver keeps the binding out.
   */
  // @ts-ignore - `null` exists at runtime (verified: `'null' in sessionDrivers`)
  // but is missing from Astro's exported driver types. Not @ts-expect-error:
  // when upstream adds it, expect-error would start failing every build.
  session: { driver: sessionDrivers.null() },

  /*
   * `platformProxy` is NOT set here. It was, for two projects, and the
   * Cloudflare adapter stopped accepting it — `Options` now derives from
   * auxiliaryWorkers | configPath | inspectorPort | persistState |
   * remoteBindings. An unknown key in an options object is dropped in silence,
   * so it read as configuration for a build that had never once applied it.
   *
   * Nothing was lost: it existed to give `astro dev` real bindings, and the
   * answer to that is `wrangler dev`, which is what the runbook already says.
   */
  adapter: cloudflare({
    imageService: 'passthrough',
  }),
  trailingSlash: 'always',
  build: { format: 'directory' },
  prefetch: { prefetchAll: true, defaultStrategy: 'hover' },
  integrations: [
    // Staging must never advertise itself. No sitemap at all off production.
    ...(isProduction
      ? [
          sitemap({
            /*
             * ⚠ EVERY PAGE THAT CARRIES `noindex` MUST BE EXCLUDED HERE.
             *
             * A URL in the sitemap is a request to index it; the same URL
             * serving `noindex` is a refusal. Search Console reports the pair
             * as "Submitted URL marked 'noindex'" — an ERROR, not a warning,
             * counted against the whole submission.
             *
             * Seen on a live site: a /search/ page was in the sitemap and
             * noindex from the day it was built. Nothing compares the two
             * lists, so it stayed invisible until the sitemap was submitted.
             *
             * Keep this list and the pages' own `noindex` in step. The 404 is
             * never emitted here. Add a page to BOTH or to NEITHER.
             */
            filter: (page) =>
              !page.includes('/thank-you') &&
              !page.includes('/search') &&
              /* Legal pages carry their own `noindex`, and unlike a rendered
                 page it is readable here — so this half derives instead of
                 being a second list to keep in step. */
              !NOINDEX_LEGAL.some((route) => new URL(page).pathname === route),
            serialize(item) {
              if (item.url === `${SITE_URL}/`) item.priority = 1.0;
              const lastmod = LASTMOD.get(new URL(item.url).pathname);
              if (lastmod) item.lastmod = lastmod;
              return item;
            },
          }),
        ]
      : []),
  ],
  markdown: {
    // Markdown images ship as root-relative paths the dev server can serve
    // directly; this plugin adds srcset and intrinsic dimensions at build time.
    processor: satteri({ hastPlugins: [hastMedia] }),
    shikiConfig: { theme: 'github-dark' },
  },
  vite: {
    build: { cssMinify: 'lightningcss' },
  },
});
