import { defineHastPlugin } from 'satteri';
// Generated by `npm run media`. Empty on a fresh project — that is fine.
import manifest from '../data/image-manifest.json' with { type: 'json' };

/** `/img/blog/name-1200.webp` → `blog/name`, the manifest key. */
function manifestKey(src) {
  const match = /^\/img\/(.+)-\d+\.webp$/.exec(typeof src === 'string' ? src : '');
  return match ? match[1] : null;
}

/**
 * Upgrades markdown output at build time.
 *
 *  - <img> gains srcset/sizes and intrinsic width/height from the media
 *    manifest, so article bodies never shift as images load. The markdown
 *    itself keeps a plain root-relative path — portable, and the dev server
 *    serves it directly.
 *  - <table> is wrapped in a scroll container, so a wide table scrolls itself
 *    rather than making the whole page scroll sideways on a phone.
 *
 * Written against Sätteri's native hast API rather than rehype: the legacy
 * rehype path needs @astrojs/markdown-remark and swaps the whole pipeline back
 * to unified, which is a dependency and a slowdown for no gain here.
 */
export const hastMedia = defineHastPlugin({
  name: 'media-manifest',
  element: [
    {
      filter: ['img'],
      visit(node, ctx) {
        const entry = manifest[manifestKey(node.properties?.src)];
        if (!entry) return;
        ctx.setProperty(node, 'srcset', entry.srcset);
        ctx.setProperty(node, 'sizes', '(min-width: 46rem) 44rem, 92vw');
        ctx.setProperty(node, 'width', entry.width);
        ctx.setProperty(node, 'height', entry.height);
        if (!node.properties?.loading) ctx.setProperty(node, 'loading', 'lazy');
        if (!node.properties?.decoding) ctx.setProperty(node, 'decoding', 'async');
      },
    },
    {
      filter: ['table'],
      visit(node, ctx) {
        const parent = ctx.parent(node);
        if (parent?.type === 'element' && parent.properties?.className?.includes?.('table-scroll')) return;
        ctx.wrapNode(node, {
          type: 'element',
          tagName: 'div',
          properties: { className: ['table-scroll'] },
          children: [],
        });
      },
    },
  ],
});
