/**
 * Per-route `lastmod` for the sitemap.
 *
 * Reads src/data/lastmod.json, which is generated by `npm run lastmod` and
 * committed. This module does no git work — it exists so astro.config.mjs can
 * stay readable.
 *
 * ── WHY THE DATES ARE COMMITTED DATA AND NOT READ FROM git HERE ────────────
 * The first version shelled out to `git log` during the build. It produced
 * correct dates locally and NOTHING in production: Cloudflare Workers Builds
 * shallow-clones, so per-file history does not exist there, and the module's
 * own shallow guard correctly refused to stamp all 23 pages with one date.
 *
 * The guard was right; depending on history the build may not have been given
 * was the mistake. Confirmed after deploying — the live sitemap had zero
 * `lastmod` elements while the local build had 23.
 *
 * ── WHY NOT JUST STAMP THE BUILD TIME ─────────────────────────────────────
 * Because it claims every page changed on every deploy, including deploys that
 * only touched a script. Google uses `lastmod` where a site's values are
 * consistently accurate and discounts them where they are not, so a
 * plausible-looking wrong date does not buy a faster re-crawl — it spends the
 * credibility that would have earned one.
 *
 * ── WHY LAYOUT AND NAV CHANGES DO NOT MOVE ANY DATE ───────────────────────
 * An earlier cut treated src/layouts/Base.astro and src/data/nav.ts as sources
 * for every route, reasoning that a footer link really does change all 23
 * documents. True, and still wrong: it collapsed every date to the same day,
 * which from outside is indistinguishable from the build-timestamp failure
 * above and carries no prioritisation signal at all. Google's guidance asks
 * for the last date a page's CONTENT changed significantly and says explicitly
 * not to bump it for navigation or boilerplate.
 *
 * If the JSON is missing or unreadable, no `lastmod` is emitted anywhere.
 * "I don't know" is a valid thing for a sitemap to say; guessing is not.
 */

import { readFileSync } from 'node:fs';

export function lastmodByRoute() {
  try {
    return new Map(Object.entries(JSON.parse(readFileSync('src/data/lastmod.json', 'utf8'))));
  } catch {
    console.warn('[sitemap] src/data/lastmod.json missing — omitting lastmod. Run `npm run lastmod`.');
    return new Map();
  }
}
