/**
 * Copy ../template into ./template so `npm pack` can include it.
 *
 * The template is NOT duplicated in the repository — this runs at pack time and
 * `postpack` deletes it again. A committed second copy is a second thing to
 * keep in step, and it is the copy that goes stale silently.
 *
 * ── npm STRIPS .gitignore FROM PUBLISHED PACKAGES ──────────────────────────
 * Long-standing, documented npm behaviour and the reason every scaffolding tool
 * carries this workaround. It is not cosmetic here: the template's .gitignore
 * is what keeps `.dev.vars` — the file holding BREVO_API_KEY and the leads
 * export token — out of the repository. A scaffolded site without it invites
 * the first `git add -A` to commit live secrets, and nothing would report it.
 *
 * So it ships renamed, and index.mjs renames it back on the way out.
 */

import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, renameSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, '..', 'template');
const dest = join(here, 'template');

if (!existsSync(src)) {
  console.error(`prepack: ${src} not found — run this from the kit repo.`);
  process.exit(1);
}

rmSync(dest, { recursive: true, force: true });

/*
 * ── COPY WHAT GIT TRACKS, NOT WHAT THE DISK HAPPENS TO HOLD ────────────────
 * This was a hand-maintained denylist — node_modules, dist, .astro, .wrangler,
 * recon, shots, .dev.vars — and it did what denylists do.
 *
 * ⚠ `template/docs/handover.pdf` REACHED A PACK. It is generated by
 *   `npm run handover`, it is ignored by `template/.gitignore` (`docs/*.pdf`),
 *   and it was still copied, because the ignore file is renamed to `gitignore`
 *   for publishing and npm therefore stops honouring it. The denylist had never
 *   heard of it. That PDF was the template placeholder, so nothing leaked — but
 *   the same path would have shipped a real client's rendered handover from any
 *   machine that had run the command.
 *
 *   `CLAUDE.md` says it plainly: a denylist tests for the mistakes you already
 *   made. Git already maintains the correct list, so ask git.
 *
 * The repo is the source of truth: if a file is not tracked, it is not part of
 * the template, and a published package should never depend on which commands
 * happen to have been run on the packer's laptop.
 */
let tracked;
try {
  tracked = execFileSync('git', ['ls-files', '-z', '--', 'template'], {
    cwd: join(here, '..'),
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
  })
    .split('\0')
    .filter(Boolean);
} catch (err) {
  console.error(
    'prepack: could not ask git which template files are tracked.\n' +
      '  Publishing must happen from a git checkout — falling back to copying the\n' +
      '  working tree would ship whatever artefacts are on this machine.\n' +
      `  ${err.message}`,
  );
  process.exit(1);
}

if (!tracked.length) {
  console.error('prepack: git reports no tracked files under template/. Refusing to pack.');
  process.exit(1);
}

for (const rel of tracked) {
  /* git always reports forward slashes; join() gives the platform separator. */
  const parts = rel.split('/').slice(1);
  const to = join(dest, ...parts);
  mkdirSync(dirname(to), { recursive: true });
  cpSync(join(here, '..', ...rel.split('/')), to);
}

/* See the note above. `.npmrc` would be stripped too; the template has none. */
for (const [from, to] of [['.gitignore', 'gitignore']]) {
  const f = join(dest, from);
  if (existsSync(f)) renameSync(f, join(dest, to));
}

/* A committed .dev.vars would be a live secret in a public package. The filter
   above excludes it; assert rather than trust, because the cost is unbounded. */
for (const forbidden of ['.dev.vars', 'node_modules', 'dist', 'recon', 'shots', join('docs', 'handover.pdf')]) {
  if (existsSync(join(dest, forbidden))) {
    console.error(`prepack: ${forbidden} reached the package. Refusing to pack.`);
    process.exit(1);
  }
}

console.log(`prepack: ${tracked.length} tracked file(s) staged`);

console.log('prepack: template staged for packing');
